# encoding: utf-8
module Holidays
  # This file is generated by the Ruby Holidays gem.
  #
  # Definitions loaded: data/jewlr.yaml, data/north_america_informal.yaml
  #
  # To use the definitions in this file, load it right after you load the
  # Holiday gem:
  #
  #   require 'holidays'
  #   require 'holidays/us'
  #
  # All the definitions are available at https://github.com/alexdunae/holidays
  module Jewlr # :nodoc:
    def self.defined_regions
      [:jewlr]
    end

    def self.holidays_by_month
      {
      0 =>  [
              {:function => lambda { |year| Holidays.easter(year)-2 }, :function_id => "easter(year)-2", :type => :informal, :name => "Good Friday", :regions => [:jewlr]}
            ],
      1 =>  [
              {:mday => 1, :observed => lambda { |date| Holidays.to_weekday_if_weekend(date) }, :observed_id => "to_weekday_if_weekend", :name => "New Year's Day", :regions => [:jewlr]}
            ],
      2 =>  [
              {:wday => 1, :week => 3, :name => "Family Day", :regions => [:jewlr]}
            ],
      5 =>  [
              {:function => lambda { |year| Holidays.ca_victoria_day(year) }, :function_id => "ca_victoria_day(year)", :name => "Victoria Day", :regions => [:jewlr]}
            ],
      7 =>  [
              {:mday => 1, :observed => lambda { |date| Holidays.to_monday_if_sunday(date) }, :observed_id => "to_monday_if_sunday", :name => "Canada Day", :regions => [:jewlr]}
            ],
      8 =>  [
              {:wday => 1, :week => 1, :name => "Civic Holiday", :regions => [:jewlr]}
            ],
      9 =>  [
              {:wday => 1, :week => 1, :name => "Labour Day", :regions => [:jewlr]}
            ],
      10 => [
              {:wday => 1, :week => 2, :name => "Thanksgiving", :regions => [:jewlr]}
            ],
      12 => [
              {:mday => 24, :name => "Christmas Eve", :regions => [:jewlr]},
              {:mday => 25, :observed => lambda { |date| Holidays.to_weekday_if_weekend(date) }, :observed_id => "to_weekday_if_weekend", :name => "Christmas Day", :regions => [:jewlr]},
              {:mday => 26, :observed => lambda { |date| Holidays.to_weekday_if_weekend(date) }, :observed_id => "to_weekday_if_weekend", :name => "Boxing Day", :regions => [:jewlr]},
              {:mday => 31, :name => "New Years Eve", :regions => [:jewlr]}
            ]
      }
    end
  end

  # Monday on or before May 24
  def self.ca_victoria_day(year)
    date = Date.civil(year,5,24)
    if date.wday > 1
      date -= (date.wday - 1)
    elsif date.wday == 0
      date -= 6
    end
    date
  end

end

Holidays.merge_defs(Holidays::Jewlr.defined_regions, Holidays::Jewlr.holidays_by_month)
